[app]
debug = true
swag = true
filrepApi = "https://api.filrep.io/api"
filecoinApi = "https://api.node.glif.io/rpc/v0"
#filecoinApi = "https://api.chain.love/rpc/v1"
jwtSecret = "7b2274797065223a224853323536222c22707269766174655f6b6579223a226b4238424c6d6765512f4a34714a4c7a6635657562544c67777454594332356f763271372f766e58446e773d227d"
passwordSalt = "6a9741"
publishDate = "2022-06-16T00:00:00Z"
officialWebsite = "https://filfind.info"
officialEmail = "support@filfind.info"

[server]
httpPort = 9095
readTimeout = 60
writeTimeout = 60

[database]
type = "mysql"
dsn = "filfind:filfind@tcp(127.0.0.1)/filfind?charset=utf8&parseTime=True&loc=Local"

[smtp]
[smtp.basic]
host = "smtpout.secureserver.net:25"
user = ""
password = ""